Repository ETI-Oct2020-Team5/RatVenture, pull requests merged in 2020-12, with the labels that each got.

#6 - Refactored the code for 'Main Menu' and added the feature of 'View …
  .vscode/settings.json
  RatVenture.py
Labels: enhancement

#10 added "Rest" function
  RatVenture.py
  backup.py
  player.txt
Labels: Requirement

#19 Refactored code (Pytest, Ratventure)
  RatVenture.py
  __pycache__/RatVenture.cpython-39.pyc
  __pycache__/test_ratventure_functions.cpython-39-pytest-6.1.2.pyc
  __pycache__/test_ratventure_functions.cpython-39.pyc
  test_ratventure_functions.py
Labels: enhancement

#30 Lennon
  RatVenture.py
  __pycache__/RatVenture.cpython-39.pyc
  __pycache__/test_ratventure_functions.cpython-39-pytest-6.1.2.pyc
Labels: enhancement

#37 Lennon
  RatVenture.py
  __pycache__/RatVenture.cpython-39.pyc
  __pycache__/test_ratventure_functions.cpython-39-pytest-6.1.2.pyc
  test_ratventure_functions.py
Labels: Requirement

#51 Documentation of savegame, resumegame, exitgame features
  RatVenture.py
Labels: documentation

#52 Refined herostats pytest to test for day as well
  RatVenture.py
  __pycache__/RatVenture.cpython-39.pyc
  __pycache__/test_ratventure_functions.cpython-39-pytest-6.1.2.pyc
  test_ratventure_functions.py
Labels: TestCode

#53 no changes made
  RatVenture.py
  __pycache__/RatVenture.cpython-39.pyc
  __pycache__/test_ratventure_functions.cpython-39-pytest-6.1.2.pyc
  backup.py
  savegame.json
  test_ratventure_functions.py
Labels: bug

#68 Move validation
  RatVenture.py
Labels: bug

#76 Lennon
  RatVenture.py
  __pycache__/RatVenture.cpython-39.pyc
  __pycache__/test_ratventure_functions.cpython-39-pytest-6.1.2.pyc
  test_ratventure_functions.py
Labels: bug

#77 Debugged newgame
  RatVenture.py
Labels: bug, documentation
